// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9EhVf53V1-KL0i6tTk6cBEDnqDlyrNmk',
    appId: '1:512392271056:web:0949cad955b2af61ddbad5',
    messagingSenderId: '512392271056',
    projectId: 'newnew-e6465',
    authDomain: 'newnew-e6465.firebaseapp.com',
    storageBucket: 'newnew-e6465.firebasestorage.app',
    measurementId: 'G-6FTN5WET67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuiBShMwAbwxCvVKk2cdlJVZUPG4hgwtY',
    appId: '1:512392271056:android:52ed81bd739925c2ddbad5',
    messagingSenderId: '512392271056',
    projectId: 'newnew-e6465',
    storageBucket: 'newnew-e6465.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIvg_LOw4cQuRrwyk6sa1Y4sBwXDL65Wc',
    appId: '1:512392271056:ios:a3cd90d1f9fac839ddbad5',
    messagingSenderId: '512392271056',
    projectId: 'newnew-e6465',
    storageBucket: 'newnew-e6465.firebasestorage.app',
    iosBundleId: 'com.example.dummyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIvg_LOw4cQuRrwyk6sa1Y4sBwXDL65Wc',
    appId: '1:512392271056:ios:a3cd90d1f9fac839ddbad5',
    messagingSenderId: '512392271056',
    projectId: 'newnew-e6465',
    storageBucket: 'newnew-e6465.firebasestorage.app',
    iosBundleId: 'com.example.dummyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9EhVf53V1-KL0i6tTk6cBEDnqDlyrNmk',
    appId: '1:512392271056:web:618d7fe97e391adfddbad5',
    messagingSenderId: '512392271056',
    projectId: 'newnew-e6465',
    authDomain: 'newnew-e6465.firebaseapp.com',
    storageBucket: 'newnew-e6465.firebasestorage.app',
    measurementId: 'G-1HM4DR66MR',
  );
}
